version: '3.2'
services:
  web:
    volumes:
      - ./:/usr/share/nginx/html/
    image: nginx:1.15.5
  python-redis:
    image: krajewskim/python-api:redis
    ports:
      - 5002:5002
    depends_on: 
      - redis
  redis:
    image: "redis"