apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-pod
spec:
  volumes:
    - name: servicejson
      configMap:
        name: configuration
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "while true;do sleep 5;cat /etc/config/service-b.config;done" ]
      volumeMounts:
        - name: servicejson
          mountPath: /etc/config
  restartPolicy: Never